"""Generate compact LVGL I4 color glyphs from the pinned OFL Noto color font.

Requires Pillow and fonttools. Pass --font for an already downloaded source;
otherwise the exact source in emoji-color.json is downloaded into memory.
Uncovered characters continue through the existing monochrome font fallback.
"""
import argparse
import hashlib
import io
import json
from pathlib import Path
import urllib.request

from fontTools.ttLib import TTFont
from PIL import Image, ImageOps


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', type=Path)
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    config = json.loads((root / 'emoji-color.json').read_text())
    data = args.font.read_bytes() if args.font else urllib.request.urlopen(config['source'], timeout=60).read()
    if hashlib.sha256(data).hexdigest() != config['sha256']:
        raise ValueError('Source font checksum does not match emoji-color.json')
    font = TTFont(io.BytesIO(data))
    cmap = font.getBestCmap()
    strike = font['CBDT'].strikeData[0]
    points = set()
    for span in config['ranges']:
        limits = [int(part, 16) for part in span.split('-')]
        points.update(range(limits[0], limits[-1] + 1))
    size = config['size']
    if size % 2:
        raise ValueError('I4 glyph width must be even')
    lines = ['/* Generated by tools/esp32-editor/generate-color-emoji.py.',
             ' * Noto Color Emoji, Copyright 2013 Google LLC; SIL OFL 1.1.',
             ' * See OFL-emoji.txt and emoji-color.json for source and coverage. */']
    entries = []
    total = 0
    for point in sorted(points):
        name = cmap.get(point)
        if name not in strike:
            continue
        glyph = strike[name]
        source = Image.open(io.BytesIO(glyph.imageData)).convert('RGBA')
        image = ImageOps.contain(source, (size, size), Image.Resampling.LANCZOS)
        tile = Image.new('RGBA', (size, size))
        tile.alpha_composite(image, ((size - image.width) // 2, (size - image.height) // 2))
        indexed = tile.quantize(colors=16, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
        palette = indexed.getpalette('RGBA')
        raw = bytearray()
        for i in range(16):
            r, g, b, a = palette[i * 4:i * 4 + 4]
            raw.extend((b, g, r, a))  # LVGL palette is BGRA8888.
        pixels = indexed.tobytes()
        raw.extend((pixels[i] << 4) | pixels[i + 1] for i in range(0, len(pixels), 2))
        total += len(raw) + 40  # Include image descriptor and lookup entry on ESP32.
        symbol = f'emoji_{point:x}'
        lines.append(f'static const uint8_t {symbol}_pixels[] = {{')
        lines.extend('    ' + ','.join(f'0x{b:02x}' for b in raw[i:i+24]) + ',' for i in range(0, len(raw), 24))
        lines.extend(['};', f'static const lv_image_dsc_t {symbol} = {{',
                      f'    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_I4, .w = {size}, .h = {size}, .stride = {size // 2}}},',
                      f'    .data_size = sizeof({symbol}_pixels), .data = {symbol}_pixels,', '};'])
        entries.append(f'    {{0x{point:x}, &{symbol}}},')
    if total > config['max_asset_bytes']:
        raise ValueError(f'Color emoji exceed flash budget: {total} bytes')
    lines.extend(['static const struct { uint32_t codepoint; const lv_image_dsc_t *image; } color_glyphs[] = {', *entries, '};'])
    target = root.parents[1] / 'apps/esp32/lvgl_port/operit_emoji_color.inc'
    target.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(f'{len(entries)} color glyphs, approximately {total} bytes of flash: {target}')


if __name__ == '__main__':
    main()
